name: Build & Publish Debug APK

on:
  push:
    branches:
      - release-action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup java11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Call wrapper task
        run: gradle wrapper
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        if: steps.create_tag.outputs.successful
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Example.apk
          asset_content_type: application/zip