name: Tagging

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Bump tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag if necessary
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        WITH_V: true
